package httpserver

import (
	"embed"
	"encoding/json"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/nicolasb114/pd-status-wall/internal/model"
)

//go:embed all:webassets/display
var displayFS embed.FS

//go:embed all:webassets/admin
var adminFS embed.FS

func displaySub() fs.FS {
	sub, err := fs.Sub(displayFS, "webassets/display")
	if err != nil {
		panic(err)
	}
	return sub
}

func adminSub() fs.FS {
	sub, err := fs.Sub(adminFS, "webassets/admin")
	if err != nil {
		panic(err)
	}
	return sub
}

var displayFileServer = noCacheHandler(http.FileServer(http.FS(displaySub())))
var adminFileServer = noCacheHandler(http.FileServer(http.FS(adminSub())))

// noCacheHandler prevents browsers from caching the HTML/CSS/JS shell. This
// app is a long-running local binary that gets upgraded in place; without
// this, a browser tab left open across an upgrade (or even just revisited
// later) can keep serving a stale cached page indefinitely, which looks
// exactly like the fix "didn't take."
func noCacheHandler(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cache-Control", "no-store")
		next.ServeHTTP(w, r)
	})
}

// handleDisplay serves the video wall page and its static assets (CSS/JS)
// from the same route tree - no login required, per spec.
func (s *Server) handleDisplay(w http.ResponseWriter, r *http.Request) {
	displayFileServer.ServeHTTP(w, r)
}

// handleAdminPage serves the admin panel's static app shell and assets from
// under the /admin/ prefix. The page itself checks whether the visitor is
// authenticated (via /admin/api/config) and shows a login form or the
// settings UI accordingly - there's no separate server-rendered login route.
func (s *Server) handleAdminPage(w http.ResponseWriter, r *http.Request) {
	path := strings.TrimPrefix(r.URL.Path, "/admin")
	r2 := r.Clone(r.Context())
	if path == "" {
		// http.FileServer redirects a request that literally ends in
		// "/index.html" to "./", which would loop back to this same
		// handler - request "/" instead, which it serves directly.
		r2.URL.Path = "/"
	} else {
		r2.URL.Path = path
	}
	adminFileServer.ServeHTTP(w, r2)
}

// publicButton mirrors model.Button for the JSON API (kept separate so the
// wire format is explicit and stable even if the internal model changes).
type publicButton struct {
	Label string `json:"label"`
	URL   string `json:"url"`
}

// displayState is what /api/state returns: the current status snapshot plus
// the public branding settings the display page needs to render itself.
// It deliberately excludes anything sensitive (API key, password hash,
// CIDR allowlist).
type displayState struct {
	GeneratedAt    string         `json:"generated_at"`
	Overall        model.Status   `json:"overall"`
	OverallMessage string         `json:"overall_message"`
	StatusPageName string         `json:"status_page_name"`
	Services       []model.Node   `json:"services"`
	LogoURL        string         `json:"logo_url,omitempty"`
	BannerURL      string         `json:"banner_url,omitempty"`
	BannerFitMode  string         `json:"banner_fit_mode"`
	ThemeMode      string         `json:"theme_mode"`
	PrimaryColor   string         `json:"primary_color"`
	TextColor      string         `json:"text_color"`
	Buttons        []publicButton `json:"buttons"`
}

func (s *Server) handleState(w http.ResponseWriter, r *http.Request) {
	cfg := s.store.Get()
	snap := s.store.Snapshot()

	state := displayState{
		GeneratedAt:    snap.GeneratedAt.UTC().Format("2006-01-02T15:04:05Z07:00"),
		Overall:        snap.Overall,
		OverallMessage: snap.OverallMessage,
		StatusPageName: snap.StatusPageName,
		Services:       snap.Services,
		BannerFitMode:  cfg.BannerFitMode,
		ThemeMode:      cfg.ThemeMode,
		PrimaryColor:   cfg.PrimaryColor,
		TextColor:      cfg.TextColor,
		Buttons:        []publicButton{},
	}
	if state.Services == nil {
		state.Services = []model.Node{}
	}
	if cfg.LogoPath != "" {
		state.LogoURL = "/uploads/" + filepath.Base(cfg.LogoPath)
	}
	if cfg.BannerPath != "" {
		state.BannerURL = "/uploads/" + filepath.Base(cfg.BannerPath)
	}
	for _, b := range cfg.Buttons {
		state.Buttons = append(state.Buttons, publicButton{Label: b.Label, URL: b.URL})
	}

	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", "no-store")
	_ = json.NewEncoder(w).Encode(state)
}

// handleUploads serves logo/banner images from the local uploads directory.
// Filenames are generated by the server (see admin.go) so there is no
// user-controlled path component beyond a final base name.
func (s *Server) handleUploads(w http.ResponseWriter, r *http.Request) {
	name := strings.TrimPrefix(r.URL.Path, "/uploads/")
	if name == "" || strings.Contains(name, "/") || strings.Contains(name, "..") {
		http.NotFound(w, r)
		return
	}
	path := filepath.Join(s.store.UploadsDir(), name)
	if _, err := os.Stat(path); err != nil {
		http.NotFound(w, r)
		return
	}
	http.ServeFile(w, r, path)
}
